destination: ./_site
auto:        true
lsi:         false
server_port: 4000
pygments:    true
markdown:    maruku
permalink:   /:year/:month/:day/:title
exclude: [CNAME, Rakefile]
maruku:
  use_tex:    false
  use_divs:   false
  png_dir:    images/latex
  png_url:    /images/latex